# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 03:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='root_password',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
