# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_inventory_root_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='ssh_port',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
    ]
