# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_inventory_ssh_port'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='ssh_port',
            field=models.CharField(default='22', max_length=5),
        ),
    ]
