# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20170617_0125'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='root_password_key',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
