# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 06:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_inventory_root_password_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='name',
            field=models.CharField(blank=True, default='', max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='regions',
            field=models.CharField(blank=True, default='', max_length=70, null=True),
        ),
    ]
