# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-27 04:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cpi_index', models.IntegerField()),
                ('cpi_text', models.CharField(blank=True, default='', max_length=20)),
                ('amount', models.FloatField()),
                ('note', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
    ]
