# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-27 05:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spendingviz', '0003_entry_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='user',
        ),
    ]
